

create sequence ccandessequence;




drop table tipoespacio;
drop table tipocomercio;
drop table tipovisitante;
drop table visita;
drop table persona;
drop table espacio;
drop table horario;
drop table tipocomerciohorario;
drop table tipovisitantehorario;


CREATE TABLE tipoespacio(
    tipo VARCHAR2(255 BYTE),
    PRIMARY KEY(tipo)
);


CREATE TABLE tipocomercio(
    tipo VARCHAR2(255 BYTE),
    PRIMARY KEY(tipo)
);


CREATE TABLE tipovisitante(
    tipo VARCHAR2(255 BYTE),
    PRIMARY KEY(tipo)
);



CREATE TABLE espacio(
    idesp NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255 BYTE) NOT NULL,
    aforo NUMBER NOT NULL,
    tipoespacio VARCHAR2(255 BYTE) NOT NULL,
    personasadentro NUMBER NOT NULL,
    estado NUMBER NOT NULL,
    tipocomercio VARCHAR2(255 BYTE),
    CONSTRAINT checkpersonasadentro
    CHECK(personasadentro > 0),
    CONSTRAINT checkestado
    CHECK(estado IN (1,0)),
    FOREIGN KEY(tipocomercio) REFERENCES tipocomercio(tipo),
    FOREIGN KEY(tipoespacio) REFERENCES tipoespacio(tipo),
    /*
    tipoestablecimiento VARCHAR2(255 BYTE) NOT NULL,
    */
    PRIMARY KEY (idesp) 
);


CREATE TABLE persona(
    nombre VARCHAR2(255 BYTE) NOT NULL,
    identificacion NUMBER NOT NULL,
    email VARCHAR2(255 BYTE),
    telefono NUMBER UNIQUE NOT NULL,
    emertelefono NUMBER NOT NULL,
    emernombre VARCHAR2(255 BYTE) NOT NULL,
    establecimientodondetrabaja NUMBER,
    companiadomicilios VARCHAR2(255 BYTE),
    tipovisitante VARCHAR2(255 BYTE),
    FOREIGN KEY(establecimientodondetrabaja) REFERENCES espacio(idesp),
    FOREIGN KEY(tipovisitante) REFERENCES tipovisitante(tipo),
    PRIMARY KEY (email)
);


CREATE TABLE visita(
    idvisita NUMBER GENERATED BY DEFAULT AS IDENTITY,
    entrada TIMESTAMP NOT NULL,
    salida TIMESTAMP,
    temperatura NUMBER NOT NULL,
    emailpersona VARCHAR2(255 BYTE) NOT NULL, 
    espacioid NUMBER NOT NULL, 
    PRIMARY KEY (idvisita),
    FOREIGN KEY(emailpersona) REFERENCES persona(email),
    FOREIGN KEY(espacioid) REFERENCES espacio(idesp)

);


CREATE TABLE horario(
    idhorario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    dia VARCHAR2(255 BYTE) NOT NULL,
    horaapertura NUMBER NOT NULL,
    horacierre NUMBER NOT NULL,
    UNIQUE (dia, horaapertura, horacierre),
    PRIMARY KEY(idhorario)
);




CREATE TABLE tipocomerciohorario(
    idtipocomercio VARCHAR2(255 BYTE) NOT NULL,
    idhorario NUMBER  NOT NULL,
    PRIMARY KEY(idtipocomercio,idhorario),
    FOREIGN KEY(idtipocomercio) REFERENCES tipocomercio(tipo),
    FOREIGN KEY(idhorario) REFERENCES horario(idhorario)
);


CREATE TABLE tipovisitantehorario(
    idtipovisitante VARCHAR2(255 BYTE) NOT NULL,
    idhorario NUMBER NOT NULL,
    PRIMARY KEY(idtipovisitante,idhorario),
    FOREIGN KEY(idtipovisitante) REFERENCES tipovisitante(tipo),
    FOREIGN KEY(idhorario) REFERENCES horario(idhorario)
);



/*
RF1
*/
    
    
INSERT INTO tipoespacio(tipo)
    VALUES ('BAÑO');


INSERT INTO espacio(
    nombre,
    aforo,
    tipoespacio,
    personasadentro,
    estado)
    VALUES (
        'Baño principal',
        10,
        'BAÑO',
        20,
        1
    )
;


/*
RF2
*/


INSERT INTO tipocomercio(tipo)
    VALUES ('RESTAURANTE');
    
    
INSERT INTO tipoespacio(tipo)
    VALUES ('ESTABLECIMIENTO');


INSERT INTO espacio(
    nombre,
    aforo,
    tipoespacio,
    personasadentro,
    tipocomercio,
    estado)
    VALUES (
        'MC Donalds',
        50,
        'ESTABLECIMIENTO',
        20,
        'RESTAURANTE',
        1
    )
;

INSERT INTO tipocomercio(tipo)
    VALUES ('TIENDA');

INSERT INTO espacio(
    nombre,
    aforo,
    tipoespacio,
    personasadentro,
    tipocomercio,
    estado)
    VALUES (
        'ZARA',
        50,
        'ESTABLECIMIENTO',
        20,
        'TIENDA',
        1
    )
;


INSERT INTO tipovisitante(tipo)
    VALUES ('DOMICILIARIO');
    
INSERT INTO tipovisitante(tipo)
    VALUES ('CLIENTE');    

INSERT INTO persona(
    nombre,
    identificacion,
    email,
    telefono,
    emertelefono,
    emernombre,
    establecimientodondetrabaja,
    tipovisitante) VALUES(
    'Alfredo',
    21322872,
    'alfredo@correo.com',
    319383293,
    23948283,
    'Sofia',
    23,
    'CLIENTE');

INSERT INTO horario(
    dia,
    horaapertura,
    horacierre) VALUES (
    10,
    8,
    22);

INSERT INTO tipovisitantehorario(
    idtipovisitante,
    idhorario) VALUES (
        'DOMICILIARIO',
        1);



/*
RF3
*/


INSERT INTO tipovisitante(tipo)
    VALUES ('LECTOR_CARNET');

INSERT INTO persona(
    nombre,
    identificacion,
    email,
    telefono,
    emertelefono,
    emernombre,
    establecimientodondetrabaja,
    tipovisitante) VALUES(
    'Maria Clara',
    10029373,
    'mc@correo.com',
    3827737727,
    31749383282,
    'Santiago',
    24,
    'LECTOR_CARNET');


/*
RF4
*/

/*
REGISTRA ENTRADA
*/

INSERT INTO visita(
    entrada,
    temperatura,
    emailpersona,
    espacioid) VALUES(
    '18/10/20 12:51:00,988000000 AM',
    37.2,
    'alfredo@correo.com',
    23);
    
INSERT INTO visita(
    entrada,
    temperatura,
    emailpersona,
    espacioid) VALUES(
    '15/10/20 9:21:00,988000000 AM',
    37.2,
    'alfredo@correo.com',
    23);
/*
REGISTRA SALIDA
*/

UPDATE visita 
SET salida = '15/10/20 1:40:00,988000000 PM'
WHERE idvisita =1;


/*
RF5
*/

UPDATE ESPACIO 
SET estado = 0
WHERE idesp =2;



/*
RFC1
*/

SELECT * FROM visita 
INNER JOIN persona
    ON visita.emailpersona = persona.email
WHERE visita.espacioid = 2
AND entrada BETWEEN TO_DATE ('14-10-2020T00:00:00', 'DD-MM-YYYY"T"HH24:MI:SS') AND TO_DATE('16-10-2020T00:00:00', 'DD-MM-YYYY"T"HH24:MI:SS');

/*
RFC2
*/

SELECT COUNT(espacioid), espacioid, espacio.nombre  FROM visita
INNER JOIN espacio
    ON visita.espacioid = espacio.idesp
WHERE visita.entrada BETWEEN TO_DATE ('14-10-2020T00:00:00', 'DD-MM-YYYY"T"HH24:MI:SS') AND TO_DATE('16-10-2020T00:00:00', 'DD-MM-YYYY"T"HH24:MI:SS')
GROUP BY espacioid,espacio.nombre
ORDER BY COUNT(espacioid) desc;


/*
RFC3
*/


SELECT * 
FROM espacio
WHERE espacio.personasadentro < espacio.aforo
















